from enum import Enum

class AssetLabel(str, Enum):
    CUSTOMER_READY = "customer_ready"
    DRAFT_ASSET = "draft_asset"
    GEOMETRY_ONLY = "geometry_only"
    TEXTURE_MISSING = "texture_missing"
    UV_MISSING = "uv_missing"
    MASK_FAILED = "mask_failed"
    WEAK_SPARSE = "weak_sparse"
    WEAK_DENSE = "weak_dense"
    TABLE_CONTAMINATION = "table_contamination"
    PRODUCT_GEOMETRY_REMOVED = "product_geometry_removed"
    RECAPTURE_REQUIRED = "recapture_required"
    AI_GENERATED_FALLBACK = "ai_generated_fallback"
    HUMAN_APPROVED = "human_approved"
    HUMAN_REJECTED = "human_rejected"

class FailureReasonLabel(str, Enum):
    CAPTURE_BLURRY = "capture_blurry"
    CAPTURE_UNDEREXPOSED = "capture_underexposed"
    CAPTURE_OVEREXPOSED = "capture_overexposed"
    INSUFFICIENT_VIEWS = "insufficient_views"
    MISSING_TOP_VIEW = "missing_top_view"
    LOW_MASK_CONFIDENCE = "low_mask_confidence"
    MASK_CONTAMINATION = "mask_contamination"
    TABLE_CONTAMINATION = "table_contamination"
    WEAK_SPARSE_RECONSTRUCTION = "weak_sparse_reconstruction"
    WEAK_DENSE_RECONSTRUCTION = "weak_dense_reconstruction"
    TEXTURING_FAILED = "texturing_failed"
    UV_MISSING = "uv_missing"
    EMBEDDED_TEXTURE_MISSING = "embedded_texture_missing"
    CLEANUP_REMOVED_PRODUCT = "cleanup_removed_product"
    GLB_EXPORT_FAILED = "glb_export_failed"
    VALIDATION_FAILED = "validation_failed"
    AI_FALLBACK_USED = "ai_fallback_used"
