import pytest
from pathlib import Path
from modules.reconstruction_engine.adapter import COLMAPAdapter, ColmapCommandBuilder
from modules.operations.settings import settings
from modules.qa_validation.validator import AssetValidator
from modules.qa_validation.rules import ValidationThresholds
from unittest.mock import MagicMock, patch
import os
import json

def test_hybrid_masking_command_logic():
    """
    Verify ColmapCommandBuilder logic directly.
    """
    builder = ColmapCommandBuilder("/path/to/colmap")
    db_path = Path("database.db")
    images_dir = Path("images")
    masks_dir = Path("masks")
    
    settings.recon_hybrid_masking = True
    cmd_sfm = builder.feature_extractor(db_path, images_dir, None, 2000)
    assert "--ImageReader.mask_path" not in cmd_sfm
    
    cmd_dense = builder.stereo_fusion(Path("workspace"), Path("fused.ply"), mask_path=masks_dir)
    assert "--StereoFusion.mask_path" in cmd_dense

def test_object_filtering_validator_logic():
    """
    Verify AssetValidator object filtering rules.
    """
    validator = AssetValidator()
    base_data = {
        "poly_count": 10000,
        "texture_integrity_status": "complete",
        "material_semantic_status": "diffuse_textured",
        "bbox": {"width": 10, "height": 10, "depth": 10},
        "ground_offset": 0.0,
        "has_position_accessor": True,
        "has_normal_accessor": True,
        "has_texcoord_0_accessor": True,
    }
    
    # Isolated => Pass
    data_isolated = {**base_data, "filtering_status": "object_isolated"}
    report = validator.validate("a1", data_isolated, allow_texture_quality_skip=True)
    assert report.final_decision == "pass"
    
    # Raw => Review
    data_raw = {**base_data, "filtering_status": "scene_raw"}
    report = validator.validate("a2", data_raw, allow_texture_quality_skip=True)
    assert report.final_decision == "review"
    
    # Failed => Fail
    data_failed = {**base_data, "filtering_status": "failed"}
    report = validator.validate("a3", data_failed, allow_texture_quality_skip=True)
    assert report.final_decision == "fail"

def test_colmap_adapter_hybrid_run_commands():
    """
    1 & 2) Adapter-level unit test that monkeypatches _run_command 
       and captures the real commands generated by COLMAPAdapter.run_reconstruction.
    """
    adapter = COLMAPAdapter("/path/to/colmap")
    
    # Mock workspace preparation
    mock_prep = {
        "images_dir": Path("temp_ws/images"),
        "masks_dir": Path("temp_ws/masks"),
        "accepted_frames": 5,
        "copied_mask_count": 5,
        "match_mode_counts": {"stem": 5, "legacy": 0, "none": 0},
    }
    
    captured_commands = []
    def mock_run_command(cmd, output_dir, log_file, timeout=None):
        captured_commands.append(cmd)

    with patch.object(COLMAPAdapter, "_prepare_workspace", return_value=mock_prep), \
         patch.object(COLMAPAdapter, "_run_command", side_effect=mock_run_command), \
         patch.object(COLMAPAdapter, "_select_best_sparse_model", return_value={"path": Path("sparse/0"), "registered_images": 5, "points_3d": 1000}), \
         patch.object(COLMAPAdapter, "_validate_dense_workspace", return_value=50000), \
         patch.object(COLMAPAdapter, "_discover_mesh_candidates", return_value=["temp_ws/dense/fused.ply"]), \
         patch.object(COLMAPAdapter, "_is_valid_mesh_candidate", return_value=True), \
         patch.object(COLMAPAdapter, "_generate_dense_masks_from_feature_masks", return_value={
             "dense_mask_valid": True, 
             "dense_mask_fallback_white_ratio": 0.0,
             "dense_mask_count": 5,
             "dense_image_count": 5,
             "dense_mask_exact_matches": 5,
             "dense_mask_dimension_matches": 5,
         }), \
         patch.object(COLMAPAdapter, "_validate_dense_masks", return_value=True), \
         patch.object(COLMAPAdapter, "_write_fusion_diagnostics"), \
         patch.object(Path, "mkdir"), \
         patch.object(Path, "exists", return_value=True), \
         patch("builtins.open", MagicMock()):
        
        settings.recon_hybrid_masking = True
        result = adapter.run_reconstruction(
            input_frames=["f1.jpg", "f2.jpg", "f3.jpg", "f4.jpg", "f5.jpg"],
            output_dir=Path("temp_ws"),
            enforce_masks=True
        )

        # Assertions
        fe_cmd = next(c for c in captured_commands if "feature_extractor" in c)
        assert "--ImageReader.mask_path" not in fe_cmd, "Hybrid SfM should be unmasked"
        
        sf_cmd = next(c for c in captured_commands if "stereo_fusion" in c)
        assert "--StereoFusion.mask_path" in sf_cmd, "Hybrid Dense stage should be masked"
        
        # Diagnostics keys (D)
        required_keys = [
            "sfm_mask_mode", "dense_mask_mode", "filtering_status", 
            "dense_mask_count", "dense_image_count", "dense_mask_exact_matches", 
            "dense_mask_dimension_matches", "dense_mask_fallback_white_ratio"
        ]
        for key in required_keys:
            assert key in result, f"Missing diagnostic key: {key}"
        
        assert result["sfm_mask_mode"] == "unmasked"
        assert result["dense_mask_mode"] == "masked"
        assert result["filtering_status"] == "object_isolated"

if __name__ == "__main__":
    try:
        test_hybrid_masking_command_logic()
        test_object_filtering_validator_logic()
        test_colmap_adapter_hybrid_run_commands()
        print("Part 2 Evidence Hardening Tests PASSED.")
    except Exception as e:
        print(f"Part 2 Evidence Hardening Tests FAILED: {e}")
        import traceback
        traceback.print_exc()
